CODE_OK = 0  # 接口操作成功
CODE_VALIDATE_ERROR = 1001  # 验证有误！
CODE_INTERVAL_TIME = 1002  # 接口操作过于频繁!
CODE_SMS_ERROR = 1100  # 短信发送失败！
CODE_USER_NOT_EXISTS = 1101  # 当前用户不存在！
CODE_JWT_INVALID = 1010  # 无效的jwt token
CODE_JWT_NOT_TOKEN = 1011  # 没有找到jwt token
CODE_JWT_EXPIRED = 1012  # jwt登录已超时
CODE_IMAGE_FORMAT_ERROR = 1020  # 错误的图片格式
